- name: variables from inventory
  hosts: web
  connection: local
  tasks:
  - name: course information
    ansible.builtin.debug:
      msg: "Course is {{Course}}, Duration is {{Duration}},Tranier is {{Tranier}}"