- name: variables from inventory
  hosts: web
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}},Tranier is {{TRAINER}}"