- name: varabiles
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the verabile
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{GREET}}"

  
#first prefrence is command line
#second prefrence is Tasks
#third prefrence is file
#forth prefrence is prompt
