- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undifined variable
    ansible.builtin.debug:
      #msg: "Hello {{ person}}" it give error here person is not defined
      msg: "Hello {{ person | default('Abdul')}}"


  - name: convert string to list
    vars:
      fruits: "apple, banana, mango, orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{fruits | split(',')}}"