- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undifined variable
    ansible.builtin.debug:
      #msg: "Hello {{ person}}" it give error here person is not defined
      msg: "Hello {{ person | default('Abdul')}}"


  - name: convert string to list
    vars:
      fruits: "apple, banana, mango, orange" #string
    ansible.builtin.debug:
      msg: "Fruits are: {{fruits | split(',')}}"

  - name: convert map into list
    vars:
      course:
        name: Ansible
        Duration: 10Hrs
        Tranier: xyz
    ansible.builtin.debug:
      msg: "Course info: {{course | dict2items}}"

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'Ansible'}
      - {'key': 'Duration', 'value': '10Hrs'}
      - {'key': 'Tranier', 'value': 'xyz'}
    ansible.builtin.debug:
      msg: "Course info: {{course | items2dict}}"

  - name: upper to lower
    vars:
      name: "AbduL RiYaz"
    ansible.builtin.debug:
      msg: "Hi {{ name | lower }}"

  - name: upper to lower
    vars:
      name: "AbduL RiYaz"
    ansible.builtin.debug:
      msg: "Hi {{ name | upper }}"

  - name: find min and max number
    vars:
      number: [20,22,46,258,7896,25478,67896]
    ansible.builtin.debug:
      msg: "Min number: {{ number | min }}, Max number: {{ number | max }}"
