- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-092d2c17ac793a2f6
   sg_id: sg-025fde350db1b3a66
   ami_id: ami-09c813fb71547fc4f
   instance_type: t3.micro
   instances:
   - mysql
   - backend
   - frotend
  tasks:
  - name: install python liblaries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - botocore
    - boto3

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
  register: ec2_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
     
